/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Balance } from "./Balance";
import { BalanceCountArgs } from "./BalanceCountArgs";
import { BalanceFindManyArgs } from "./BalanceFindManyArgs";
import { BalanceFindUniqueArgs } from "./BalanceFindUniqueArgs";
import { CreateBalanceArgs } from "./CreateBalanceArgs";
import { UpdateBalanceArgs } from "./UpdateBalanceArgs";
import { DeleteBalanceArgs } from "./DeleteBalanceArgs";
import { User } from "../../user/base/User";
import { BalanceService } from "../balance.service";
@graphql.Resolver(() => Balance)
export class BalanceResolverBase {
  constructor(protected readonly service: BalanceService) {}

  async _balancesMeta(
    @graphql.Args() args: BalanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Balance])
  async balances(
    @graphql.Args() args: BalanceFindManyArgs
  ): Promise<Balance[]> {
    return this.service.balances(args);
  }

  @graphql.Query(() => Balance, { nullable: true })
  async balance(
    @graphql.Args() args: BalanceFindUniqueArgs
  ): Promise<Balance | null> {
    const result = await this.service.balance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Balance)
  async createBalance(
    @graphql.Args() args: CreateBalanceArgs
  ): Promise<Balance> {
    return await this.service.createBalance({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Balance)
  async updateBalance(
    @graphql.Args() args: UpdateBalanceArgs
  ): Promise<Balance | null> {
    try {
      return await this.service.updateBalance({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Balance)
  async deleteBalance(
    @graphql.Args() args: DeleteBalanceArgs
  ): Promise<Balance | null> {
    try {
      return await this.service.deleteBalance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Balance): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
