/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BalanceService } from "../balance.service";
import { BalanceCreateInput } from "./BalanceCreateInput";
import { Balance } from "./Balance";
import { BalanceFindManyArgs } from "./BalanceFindManyArgs";
import { BalanceWhereUniqueInput } from "./BalanceWhereUniqueInput";
import { BalanceUpdateInput } from "./BalanceUpdateInput";

export class BalanceControllerBase {
  constructor(protected readonly service: BalanceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Balance })
  async createBalance(
    @common.Body() data: BalanceCreateInput
  ): Promise<Balance> {
    return await this.service.createBalance({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        balance: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Balance] })
  @ApiNestedQuery(BalanceFindManyArgs)
  async balances(@common.Req() request: Request): Promise<Balance[]> {
    const args = plainToClass(BalanceFindManyArgs, request.query);
    return this.service.balances({
      ...args,
      select: {
        balance: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Balance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async balance(
    @common.Param() params: BalanceWhereUniqueInput
  ): Promise<Balance | null> {
    const result = await this.service.balance({
      where: params,
      select: {
        balance: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Balance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBalance(
    @common.Param() params: BalanceWhereUniqueInput,
    @common.Body() data: BalanceUpdateInput
  ): Promise<Balance | null> {
    try {
      return await this.service.updateBalance({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          balance: true,
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Balance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBalance(
    @common.Param() params: BalanceWhereUniqueInput
  ): Promise<Balance | null> {
    try {
      return await this.service.deleteBalance({
        where: params,
        select: {
          balance: true,
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
