/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Proxy } from "./Proxy";
import { ProxyCountArgs } from "./ProxyCountArgs";
import { ProxyFindManyArgs } from "./ProxyFindManyArgs";
import { ProxyFindUniqueArgs } from "./ProxyFindUniqueArgs";
import { CreateProxyArgs } from "./CreateProxyArgs";
import { UpdateProxyArgs } from "./UpdateProxyArgs";
import { DeleteProxyArgs } from "./DeleteProxyArgs";
import { Provider } from "../../provider/base/Provider";
import { ProxyService } from "../proxy.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Proxy)
export class ProxyResolverBase {
  constructor(
    protected readonly service: ProxyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "read",
    possession: "any",
  })
  async _proxiesMeta(
    @graphql.Args() args: ProxyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Proxy])
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "read",
    possession: "any",
  })
  async proxies(@graphql.Args() args: ProxyFindManyArgs): Promise<Proxy[]> {
    return this.service.proxies(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Proxy, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "read",
    possession: "own",
  })
  async proxy(
    @graphql.Args() args: ProxyFindUniqueArgs
  ): Promise<Proxy | null> {
    const result = await this.service.proxy(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Proxy)
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "create",
    possession: "any",
  })
  async createProxy(@graphql.Args() args: CreateProxyArgs): Promise<Proxy> {
    return await this.service.createProxy({
      ...args,
      data: {
        ...args.data,

        provider: args.data.provider
          ? {
              connect: args.data.provider,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Proxy)
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "update",
    possession: "any",
  })
  async updateProxy(
    @graphql.Args() args: UpdateProxyArgs
  ): Promise<Proxy | null> {
    try {
      return await this.service.updateProxy({
        ...args,
        data: {
          ...args.data,

          provider: args.data.provider
            ? {
                connect: args.data.provider,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Proxy)
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "delete",
    possession: "any",
  })
  async deleteProxy(
    @graphql.Args() args: DeleteProxyArgs
  ): Promise<Proxy | null> {
    try {
      return await this.service.deleteProxy(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Provider, {
    nullable: true,
    name: "provider",
  })
  @nestAccessControl.UseRoles({
    resource: "Provider",
    action: "read",
    possession: "any",
  })
  async getProvider(@graphql.Parent() parent: Proxy): Promise<Provider | null> {
    const result = await this.service.getProvider(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
