/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProxyService } from "../proxy.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProxyCreateInput } from "./ProxyCreateInput";
import { Proxy } from "./Proxy";
import { ProxyFindManyArgs } from "./ProxyFindManyArgs";
import { ProxyWhereUniqueInput } from "./ProxyWhereUniqueInput";
import { ProxyUpdateInput } from "./ProxyUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProxyControllerBase {
  constructor(
    protected readonly service: ProxyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Proxy })
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProxy(@common.Body() data: ProxyCreateInput): Promise<Proxy> {
    return await this.service.createProxy({
      data: {
        ...data,

        provider: data.provider
          ? {
              connect: data.provider,
            }
          : undefined,
      },
      select: {
        country: true,
        createdAt: true,
        id: true,
        ip: true,
        port: true,

        provider: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Proxy] })
  @ApiNestedQuery(ProxyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proxies(@common.Req() request: Request): Promise<Proxy[]> {
    const args = plainToClass(ProxyFindManyArgs, request.query);
    return this.service.proxies({
      ...args,
      select: {
        country: true,
        createdAt: true,
        id: true,
        ip: true,
        port: true,

        provider: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Proxy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proxy(
    @common.Param() params: ProxyWhereUniqueInput
  ): Promise<Proxy | null> {
    const result = await this.service.proxy({
      where: params,
      select: {
        country: true,
        createdAt: true,
        id: true,
        ip: true,
        port: true,

        provider: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Proxy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProxy(
    @common.Param() params: ProxyWhereUniqueInput,
    @common.Body() data: ProxyUpdateInput
  ): Promise<Proxy | null> {
    try {
      return await this.service.updateProxy({
        where: params,
        data: {
          ...data,

          provider: data.provider
            ? {
                connect: data.provider,
              }
            : undefined,
        },
        select: {
          country: true,
          createdAt: true,
          id: true,
          ip: true,
          port: true,

          provider: {
            select: {
              id: true,
            },
          },

          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Proxy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proxy",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProxy(
    @common.Param() params: ProxyWhereUniqueInput
  ): Promise<Proxy | null> {
    try {
      return await this.service.deleteProxy({
        where: params,
        select: {
          country: true,
          createdAt: true,
          id: true,
          ip: true,
          port: true,

          provider: {
            select: {
              id: true,
            },
          },

          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
